/* API Keys • Owner-only provider management */
(function(){'use strict';
const $=id=>document.getElementById(id);
const SB_URL='https://bopezesfrmdxiagvvyyh.supabase.co';
const SB_KEY='sb_publishable_eLAz-YGqz0ET4n7t1g9BOA_suPeofcR';
const db=supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const session=()=>window.__sadeeqConsoleSession?.()||'';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const mask=()=> '••••••••';
async function rpc(name,args){return db.rpc(name,args)}
function status(text,ok=false){const e=$('ak-status');if(!e)return;e.textContent=text;e.classList.remove('hidden','success','error');e.classList.add(ok?'success':'error')}
function providerHeaders(){const s=session();return {'Content-Type':'application/json','Authorization':`Bearer ${s}`}}
async function manager(payload){const s=session();if(!s){status('Owner session ta kare. Sake shiga Owner Console.');throw new Error('UNAUTHORIZED')}const r=await fetch(SB_URL+'/functions/v1/api-key-manager',{method:'POST',headers:providerHeaders(),body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch{}if(r.status===401||d.error==='UNAUTHORIZED'){status('Owner session ta kare. Sake shiga Owner Console.');throw new Error('UNAUTHORIZED')}return d}
function view(){document.querySelectorAll('.page').forEach(p=>{p.classList.add('hidden');p.classList.remove('active-page')});let root=$('page-keys');if(!root){root=document.createElement('section');root.id='page-keys';root.className='page';document.querySelector('.main-content')?.appendChild(root)}root.className='page active-page';root.innerHTML=`<div class="module-hero api-hero"><div><span class="section-label">SECURE AI PROVIDERS</span><h2>API Keys</h2><p>Owner-only provider connections, live model discovery and verified tests.</p></div><div class="module-badge">OWNER ONLY</div></div><div class="api-grid api-modern"><section class="form-panel api-config-card"><div class="panel-heading"><div><span class="section-label">PROVIDER CONFIGURATION</span><h3>Configure AI Provider</h3></div><span class="live-pill"><i></i> SECURE</span></div><label>Provider<select id="ak-provider"><option value="openrouter">OpenRouter</option><option value="google_ai_studio">Google AI Studio</option></select></label><label>Key Name<input id="ak-name" placeholder="Production AI Key" autocomplete="off"></label><label>API Key<input id="ak-key" type="password" autocomplete="new-password" placeholder="Paste provider API key"></label><label class="model-field">Model<div class="model-select-wrap"><button id="ak-model-trigger" class="model-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span id="ak-model-label">Select a model</span><b>⌄</b></button><div id="ak-model-menu" class="model-menu hidden" role="listbox"></div></div></label><div class="selected-model"><span>SELECTED MODEL</span><strong id="ak-selected-model">Not selected</strong></div><div class="button-row api-actions"><button id="ak-models" class="secondary-btn" type="button">↻ Find Models</button><button id="ak-test" class="secondary-btn" type="button">✓ Test</button><button id="ak-save" class="primary-btn" type="button">Save Key</button></div><div id="ak-status" class="inline-error hidden"></div></section><section class="form-panel saved-api-card"><div class="panel-heading"><div><span class="section-label">ACTIVE CONNECTIONS</span><h3>Saved Providers</h3></div><button id="ak-refresh" class="icon-refresh" type="button">↻</button></div><div id="ak-list" class="key-list"><div class="empty-state">Ana loda...</div></div></section></div>`;bind();load()}
function bind(){$('ak-model-trigger').onclick=e=>{e.stopPropagation();const m=$('ak-model-menu');const open=m.classList.toggle('hidden')===false;$('ak-model-trigger').setAttribute('aria-expanded',String(open));$('ak-model-trigger').closest('.model-field')?.classList.toggle('model-open',open)};$('ak-models').onclick=findModels;$('ak-test').onclick=testKey;$('ak-save').onclick=save;$('ak-refresh').onclick=load;$('ak-provider').onchange=clearModel;document.addEventListener('click',closeModel,{passive:true})}
function closeModel(e){const w=document.querySelector('.model-select-wrap');if(w&&!w.contains(e.target)){const m=$('ak-model-menu');if(m){m.classList.add('hidden');$('ak-model-trigger')?.setAttribute('aria-expanded','false');$('ak-model-trigger')?.closest('.model-field')?.classList.remove('model-open')}}}
function clearModel(){$('ak-model-label').textContent='Select a model';$('ak-selected-model').textContent='Not selected';$('ak-model-menu').innerHTML='';$('ak-model-menu').classList.add('hidden');$('ak-model-trigger').setAttribute('aria-expanded','false');$('ak-model-trigger').closest('.model-field')?.classList.remove('model-open')}
function selectModel(id){$('ak-model-label').textContent=id;$('ak-selected-model').textContent=id;$('ak-model-menu').classList.add('hidden');$('ak-model-trigger').setAttribute('aria-expanded','false');$('ak-model-trigger').closest('.model-field')?.classList.remove('model-open')}
async function findModels(){const provider=$('ak-provider').value,key=$('ak-key').value.trim();if(!key){status('Saka API key kafin nemo models.');$('ak-key').focus();return}const b=$('ak-models');b.disabled=true;b.textContent='Searching...';status('Ana neman real models...');try{const d=await manager({action:'models',provider,api_key:key});if(!d.ok){status(d.error||'Models search failed.');return}renderModels(d.models||[]);$('ak-model-menu').classList.remove('hidden');$('ak-model-trigger').setAttribute('aria-expanded','true');$('ak-model-trigger').closest('.model-field')?.classList.add('model-open');status(`An samu ${Number(d.models?.length||0).toLocaleString()} models.`,true)}catch(e){if(e.message!=='UNAUTHORIZED')status('An kasa haɗawa da provider manager.')}finally{b.disabled=false;b.textContent='↻ Find Models'}}
function renderModels(models){const menu=$('ak-model-menu');if(!models.length){menu.innerHTML='<div class="model-empty">Babu model da provider ya dawo.</div>';return}menu.innerHTML=models.slice(0,150).map((m,i)=>`<button class="model-option" type="button" role="option" data-model="${esc(m.id)}"><span class="model-number">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(m.name||m.id)}</strong><small>${esc(m.id)}</small></span><b>›</b></button>`).join('');menu.querySelectorAll('.model-option').forEach(b=>b.onclick=()=>selectModel(b.dataset.model))}
async function testKey(){const provider=$('ak-provider').value,key=$('ak-key').value.trim(),model=$('ak-selected-model').textContent.trim();if(!key||!model||model==='Not selected'){status('Saka API key kuma zabi model kafin Test.');return}const b=$('ak-test');b.disabled=true;b.textContent='Testing...';status('Ana yin real test request...');try{const d=await manager({action:'test',provider,api_key:key,model});if(d.ok)status(`✓ Successfully connected • ${Number(d.tokens||0).toLocaleString()} tokens`,true);else status(d.error||'Invalid key/model.')}catch(e){if(e.message!=='UNAUTHORIZED')status('Test request ya kasa.')}finally{b.disabled=false;b.textContent='✓ Test'}}
async function save(){const s=session(),provider=$('ak-provider').value,name=$('ak-name').value.trim(),key=$('ak-key').value.trim(),model=$('ak-selected-model').textContent.trim();if(!s){status('Owner session ta kare. Sake shiga Owner Console.');return}if(!name||!key||!model||model==='Not selected'){status('Cika Key Name, API Key kuma zabi Model.');return}const b=$('ak-save');b.disabled=true;b.textContent='Saving...';status('Ana tabbatar da key/model kafin saving...');try{const test=await manager({action:'test',provider,api_key:key,model});if(!test.ok){status(test.error||'Key/model bai wuce test ba. Ba a yi saving ba.');return}const r=await rpc('owner_save_api_key',{p_session:s,p_provider:provider,p_key_name:name,p_api_key:key,p_model:model,p_active:true});if(r.error||!r.data?.ok){status(r.data?.error||r.error?.message||'Save failed.');return}await rpc('owner_log_api_key_action',{p_session:s,p_action:'SAVE_API_KEY',p_target:name,p_details:{provider,model,test_tokens:Number(test.tokens||0)}});$('ak-key').value='';status('✓ Saved successfully • '+provider+' • '+model,true);await load()}catch(e){if(e.message!=='UNAUTHORIZED')status('Network error wajen saving. Gwada kuma.')}finally{b.disabled=false;b.textContent='Save Key'}}
async function load(){const list=$('ak-list'),s=session();if(!list)return;if(!s){list.innerHTML='<div class="empty-state">Owner session bai samu ba.</div>';return}const r=await rpc('owner_list_api_keys',{p_session:s});if(r.error||!r.data?.ok){list.innerHTML='<div class="empty-state">'+esc(r.data?.error||r.error?.message||'Unable to load API keys.')+'</div>';return}const rows=r.data.keys||[];list.innerHTML=rows.length?rows.map(k=>`<article class="key-card premium-key"><div class="key-card-main"><div class="provider-orb">${k.provider==='openrouter'?'OR':'G'}</div><div><div class="provider-pill">${esc(k.provider)}</div><h4>${esc(k.key_name)}</h4><p>${mask()} • <strong>${esc(k.model)}</strong></p><small>Last used: ${esc(k.last_used_at?new Date(k.last_used_at).toLocaleString():'Never')}<br>Requests: ${Number(k.total_requests||0).toLocaleString()} • Tokens: ${Number(k.total_tokens||0).toLocaleString()}</small></div></div><div class="key-actions"><span class="active-state ${k.active?'on':''}">${k.active?'● ACTIVE':'○ OFF'}</span><button class="toggle-key" data-id="${k.id}" data-active="${!k.active}">${k.active?'Disable':'Enable'}</button><button class="delete-key danger-btn" data-id="${k.id}">Delete</button></div></article>`).join(''):'<div class="empty-state">No API keys saved yet.</div>';list.querySelectorAll('.toggle-key').forEach(b=>b.onclick=()=>toggle(b.dataset.id,b.dataset.active==='true'));list.querySelectorAll('.delete-key').forEach(b=>b.onclick=()=>removeKey(b.dataset.id))}
async function toggle(id,active){const r=await rpc('owner_set_api_key_active',{p_session:session(),p_id:id,p_active:active});if(r.error||!r.data?.ok){status(r.data?.error||r.error?.message||'Update failed.');return}await rpc('owner_log_api_key_action',{p_session:session(),p_action:active?'ENABLE_API_KEY':'DISABLE_API_KEY',p_target:id});await load()}
async function removeKey(id){if(!confirm('Delete wannan API key?'))return;const r=await rpc('owner_delete_api_key',{p_session:session(),p_id:id});if(r.error||!r.data?.ok){status(r.data?.error||r.error?.message||'Delete failed.');return}await rpc('owner_log_api_key_action',{p_session:session(),p_action:'DELETE_API_KEY',p_target:id});await load()}
window.showSadeeqKeys=view;
})();