const SUPABASE_URL='https://bopezesfrmdxiagvvyyh.supabase.co';
const SUPABASE_KEY='sb_publishable_eLAz-YGqz0ET4n7t1g9BOA_suPeofcR';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});window.client=client;
const $=id=>document.getElementById(id);const loading=$('console-loading'),denied=$('console-denied'),consoleRoot=$('owner-console');
const pageNames={home:'Home',bots:'Bots','all-bots':'All Bots',instructions:'Instructions',webs:'Webs Joined',usage:'API Bot Usage',logs:'Audit Logs',sadeeq:'Sadeeq AI',keys:'API Keys',account:'Account & Security',playground:'Bot Playground'};let consoleSession=null;
function deny(message='Wannan Owner Console ne kawai. Ticket din shiga bai inganta ba ko ya kare.'){loading.classList.add('hidden');consoleRoot.classList.add('hidden');denied.classList.remove('hidden');const box=$('denied-message');if(box)box.textContent=message}
async function unlock(){const hash=window.location.hash.replace(/^#/,'');const params=new URLSearchParams(hash);const ticket=params.get('ticket');if(window.history.replaceState)window.history.replaceState({},document.title,window.location.pathname+window.location.search);if(!ticket){deny();return}const {data,error}=await client.rpc('redeem_owner_console_ticket',{p_ticket:ticket});if(error||typeof data!=='string'||data.length!==64){deny();return}consoleSession=data;window.__sadeeqConsoleSession=()=>consoleSession;loading.classList.add('hidden');consoleRoot.classList.remove('hidden');renderHomeShell();initConsole();await loadDashboard()}
function renderHomeShell(){const page=$('page-home');if(page)page.innerHTML=''}
function setText(id,value){const el=$(id);if(el)el.textContent=value}function number(value){return Number(value||0).toLocaleString()}function showDashboardError(message){const el=$('dashboard-error');if(!el)return;el.textContent=message;el.classList.remove('hidden')}function clearDashboardError(){$('dashboard-error')?.classList.add('hidden')}
async function loadDashboard(){return}
function initConsole(){const items=[...document.querySelectorAll('.nav-item[data-page]')],quick=[...document.querySelectorAll('.quick-action[data-page]')],title=$('page-title');const pageIds=['home','bots','all-bots','instructions','webs','usage','logs','sadeeq','keys','account','playground'];function clearInactive(name){document.querySelectorAll('.page').forEach(p=>{const keep=p.id===`page-${name}`;p.classList.toggle('hidden',!keep);p.classList.toggle('active-page',keep);if(!keep)p.replaceChildren()})}function select(name){if(!pageIds.includes(name))name='home';items.forEach(item=>item.classList.toggle('active',item.dataset.page===name));quick.forEach(item=>item.classList.toggle('active',item.dataset.page===name));title.textContent=pageNames[name]||name;clearInactive(name);if(name==='home'){window.showOwnerServerCenter?.()}else if(name==='all-bots'){window.showSadeeqAllBots?.()}else if(name==='bots'){window.showSadeeqBots?.()}else if(name==='instructions'){window.showSadeeqInstructions?.()}else if(name==='webs'){window.showWebsJoined?.()}else if(name==='usage'){window.showApiBotUsage?.()}else if(name==='logs'){window.showAuditLogs?.()}else if(name==='keys'){window.showSadeeqKeys?.()}else if(name==='account'){window.showSadeeqAccount?.()}else if(name==='sadeeq'){window.showSadeeqAI?.()}else if(name==='playground'){window.openBotPlayground?.(window.__pendingPlaygroundBotId)}closeSidebar()}
items.forEach(item=>item.addEventListener('click',()=>select(item.dataset.page)));quick.forEach(item=>item.addEventListener('click',()=>select(item.dataset.page)));const sidebar=$('sidebar'),backdrop=$('sidebar-backdrop');function openSidebar(){sidebar.classList.add('open');backdrop.classList.add('show')}function closeSidebar(){sidebar.classList.remove('open');backdrop.classList.remove('show')}window.closeSidebar=closeSidebar;$('open-sidebar')?.addEventListener('click',openSidebar);$('close-sidebar')?.addEventListener('click',closeSidebar);backdrop?.addEventListener('click',closeSidebar);select('home')}
window.addEventListener('pagehide',()=>{if(!consoleSession)return;fetch(`${SUPABASE_URL}/rest/v1/rpc/revoke_owner_console_session`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_session:consoleSession}),keepalive:true}).catch(()=>{})});unlock();