(function(){'use strict';
const SUPA='https://bopezesfrmdxiagvvyyh.supabase.co',KEY='sb_publishable_eLAz-YGqz0ET4n7t1g9BOA_suPeofcR';
const db=window.supabase.createClient(SUPA,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const CHAT_URL=SUPA+'/functions/v1/owner-server-chat';
const $=id=>document.getElementById(id); const session=()=>typeof window.__sadeeqConsoleSession==='function'?window.__sadeeqConsoleSession():null;
let settings={bots_enabled:true,server_prompt_mode:false};
function css(){if($('owner-home-css'))return;const s=document.createElement('style');s.id='owner-home-css';s.textContent=`
#page-home .owner-home{width:100%;margin:0;padding:0}.server-board{width:100%;height:700px;box-sizing:border-box;display:flex;flex-direction:column;padding:18px;border:1px solid rgba(143,119,255,.2);border-radius:24px;background:linear-gradient(145deg,rgba(8,15,35,.98),rgba(4,8,22,.96));box-shadow:0 20px 60px rgba(0,0,0,.22)}.server-board.prompt{border-color:rgba(244,211,122,.25)}.server-toolbar{display:flex;align-items:center;justify-content:flex-end;gap:14px;padding:0 2px 14px;border-bottom:1px solid rgba(255,255,255,.06)}.server-control{display:flex;align-items:center;gap:8px;color:#aeb8d0;font-size:11px;font-weight:800}.server-control button{width:46px;height:26px;border:0;border-radius:99px;padding:3px;background:#202941;cursor:pointer}.server-control button i{display:block;width:20px;height:20px;border-radius:50%;background:#78849d;transition:.2s}.server-control button.on{background:linear-gradient(100deg,#5a39e8,#a848d8)}.server-control button.on i{transform:translateX(20px);background:#fff}.server-board-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0}.server-board-head h3{margin:2px 0;font-size:17px}.board-badge{font-size:9px;font-weight:900;letter-spacing:.08em;padding:7px 10px;border-radius:999px;color:#8ce8c4;background:rgba(67,224,163,.06);border:1px solid rgba(67,224,163,.2)}.board-badge.prompt{color:#f4d37a;border-color:rgba(244,211,122,.2)}.server-messages{flex:1;min-height:0;overflow:auto;padding:8px 2px}.server-msg{max-width:88%;margin:8px 0;padding:12px 14px;border-radius:15px;font-size:12px;line-height:1.6;white-space:pre-wrap}.server-msg.user{margin-left:auto;background:linear-gradient(135deg,#4d328d,#5c3ba2)}.server-msg.assistant{background:rgba(16,26,53,.76);border:1px solid rgba(143,119,255,.13)}.server-msg.system{margin:10px auto;max-width:96%;font-size:10px;color:#8d99b3;text-align:center;background:rgba(255,255,255,.025)}.server-compose{display:flex;gap:9px;margin-top:12px}.server-compose input{flex:1;min-width:0}.server-compose button{width:auto;margin:0;padding:0 18px}@media(max-width:650px){.server-board{height:700px}.server-toolbar{justify-content:space-between}.server-compose{flex-direction:column}.server-compose button{min-height:44px}}`;document.head.appendChild(s)}
function add(root,role,text){const d=document.createElement('div');d.className='server-msg '+role;d.textContent=text;root.appendChild(d);root.scrollTop=root.scrollHeight}
async function getSettings(){const s=session();if(!s)return;const r=await db.rpc('get_owner_system_settings',{p_session:s});if(!r.error&&r.data)settings=r.data}
async function setSetting(key,value){const s=session();if(!s)throw Error('NO_SESSION');const args={p_session:s,p_bots_enabled:null,p_server_prompt_mode:null};args[key==='bots_enabled'?'p_bots_enabled':'p_server_prompt_mode']=value;const r=await db.rpc('set_owner_system_settings',args);if(r.error)throw r.error;settings=r.data||settings;render()}
function render(){const p=$('page-home');if(!p)return;css();const prompt=!!settings.server_prompt_mode;p.innerHTML=`<div class="owner-home"><section class="server-board ${prompt?'prompt':''}"><div class="server-toolbar"><div class="server-control"><span>Mode</span><button id="server-mode-switch" class="${prompt?'on':''}" aria-label="Mode"><i></i></button></div><div class="server-control"><span>Power</span><button id="bots-master-switch" class="${settings.bots_enabled?'on':''}" aria-label="Power"><i></i></button></div></div><div class="server-board-head"><div><span class="section-label">${prompt?'SERVER PROMPT':'SERVER CHAT'}</span><h3>${prompt?'Prompt Mode':'Admin Chat'}</h3></div><span class="board-badge ${prompt?'prompt':''}">${prompt?'PROMPT ON':'CHAT ON'}</span></div><div id="server-messages" class="server-messages"><div class="server-msg system">${prompt?'Prompt Mode a shirye yake. Rubuta umarnin owner.':'Chat Mode a shirye yake. Yi magana da uwar garke.'}</div></div><div class="server-compose"><input id="server-input" maxlength="8000" placeholder="${prompt?'Rubuta umarni...':'Tambayi Sadeeq Server...'}"><button id="server-send" class="primary-btn" type="button">${prompt?'Execute':'Send'}</button></div></section></div>`;
$('bots-master-switch').onclick=async()=>{const b=$('bots-master-switch');b.disabled=true;try{await setSetting('bots_enabled',!settings.bots_enabled)}catch{alert('Ba a iya canza Power ba.')}finally{b.disabled=false}};
$('server-mode-switch').onclick=async()=>{const b=$('server-mode-switch');b.disabled=true;try{await setSetting('server_prompt_mode',!settings.server_prompt_mode)}catch{alert('Ba a iya canza Mode ba.')}finally{b.disabled=false}};
$('server-send').onclick=sendServer;$('server-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendServer()}}}
async function sendServer(){const input=$('server-input'),root=$('server-messages'),button=$('server-send'),text=input?.value.trim();if(!text||!session())return;input.value='';add(root,'user',text);button.disabled=true;button.textContent='...';try{const r=await fetch(CHAT_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:session(),mode:settings.server_prompt_mode?'prompt':'chat',message:text})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)add(root,'system',d?.error||'An kasa aiwatar da request.');else if(settings.server_prompt_mode)add(root,'assistant',`✓ ${d.action||'An aiwatar da umarnin.'}${d.result?`\n${JSON.stringify(d.result,null,2)}`:''}`);else add(root,'assistant',d.answer||'Babu amsa.')}catch{add(root,'system','Network error. Gwada kuma.')}finally{button.disabled=false;button.textContent=settings.server_prompt_mode?'Execute':'Send'}}
window.showOwnerServerCenter=async function(){await getSettings();render()};
})();