/* Sadeeq AI Hub • Level 10: Global Instructions */
(function(){
'use strict';
const page=()=>document.getElementById('page-instructions');
const session=()=>typeof window.__sadeeqConsoleSession==='function'?window.__sadeeqConsoleSession():null;
const sb=()=>window.supabase.createClient('https://bopezesfrmdxiagvvyyh.supabase.co','sb_publishable_eLAz-YGqz0ET4n7t1g9BOA_suPeofcR',{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
function styles(){if(document.getElementById('level10-instructions-css'))return;const s=document.createElement('style');s.id='level10-instructions-css';s.textContent=`
.instructions-page{max-width:920px;margin:0 auto;animation:l10in .45s ease both}.instructions-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:20px}.instructions-head h2{margin:6px 0}.instructions-head p{margin:0;color:#7f8ba7;line-height:1.7}.instructions-badge{display:inline-flex;align-items:center;gap:8px;padding:8px 11px;border:1px solid rgba(143,119,255,.2);border-radius:999px;color:#9b8cff;background:rgba(139,108,255,.06);font-size:9px;font-weight:800;letter-spacing:.08em;white-space:nowrap}.instructions-card{position:relative;overflow:hidden;padding:26px;border:1px solid rgba(143,119,255,.18);border-radius:24px;background:linear-gradient(145deg,rgba(9,16,38,.97),rgba(5,9,24,.95));box-shadow:0 20px 65px rgba(0,0,0,.25)}.instructions-card:before{content:"";position:absolute;inset:-1px;pointer-events:none;background:radial-gradient(circle at 0 0,rgba(141,114,255,.12),transparent 30%),radial-gradient(circle at 100% 100%,rgba(194,160,68,.07),transparent 28%)}.instructions-inner{position:relative;z-index:1}.instructions-label{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.instructions-label strong{font-size:13px}.instructions-label span{font-size:9px;color:#6f7c96}.instructions-editor{width:100%;min-height:360px;resize:vertical;box-sizing:border-box;border:1px solid rgba(139,124,255,.2);border-radius:18px;background:linear-gradient(145deg,#030716,#0a1129);color:#f7f8ff;padding:18px;font:13px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace;outline:none;transition:.2s ease}.instructions-editor:focus{border-color:rgba(155,130,255,.75);box-shadow:0 0 0 4px rgba(127,95,255,.09),0 0 35px rgba(127,95,255,.08)}.instructions-footer{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:16px}.instructions-count{color:#68758f;font-size:10px}.instructions-save{min-width:190px}.instructions-feedback{margin-top:14px;padding:12px 14px;border-radius:13px;text-align:center;font-size:11px}.instructions-feedback.success{color:#8ce8c4;background:rgba(10,55,43,.3);border:1px solid rgba(67,224,163,.22)}.instructions-feedback.error{color:#ff9cac;background:rgba(73,16,31,.3);border:1px solid rgba(245,96,123,.25)}.instructions-note{margin-top:18px;padding:15px;border:1px solid rgba(244,211,122,.13);border-radius:15px;background:rgba(244,211,122,.035);color:#9ca8bf;font-size:11px;line-height:1.7}.instructions-note b{color:#f4d37a}@keyframes l10in{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@media(max-width:700px){.instructions-head{align-items:flex-start;flex-direction:column}.instructions-card{padding:19px}.instructions-footer{align-items:stretch;flex-direction:column}.instructions-save{width:100%}.instructions-editor{min-height:320px}}
`;document.head.appendChild(s)}
function feedback(msg,type){const e=document.getElementById('instructions-feedback');if(e){e.textContent=msg;e.className='instructions-feedback '+type;e.classList.remove('hidden')}}
async function render(){const p=page();if(!p)return;styles();p.className='page active-page';p.innerHTML=`<div class="instructions-page"><div class="instructions-head"><div><span class="section-label">SYSTEM KNOWLEDGE</span><h2>Instructions</h2><p>Wannan shi ne <b>base instructions</b> na system. Duk bot da ba shi da nasa instructions zai yi amfani da wannan a matsayin fallback.</p></div><span class="instructions-badge"><span class="status-dot"></span> SUPABASE SOURCE</span></div><section class="instructions-card"><div class="instructions-inner"><div class="instructions-label"><strong>Global Base Instructions</strong><span id="instructions-updated">Ana loda...</span></div><textarea id="global-instructions" class="instructions-editor" maxlength="50000" spellcheck="false" placeholder="Rubuta bayanan da uwar garke za ta yi amfani da su wajen bada amsa..."></textarea><div class="instructions-footer"><span id="instructions-count" class="instructions-count">0 / 50,000</span><button id="save-global-instructions" class="primary-btn instructions-save" type="button">Save Instructions</button></div><div id="instructions-feedback" class="instructions-feedback hidden"></div><div class="instructions-note"><b>Fallback rule:</b> Idan <b>Bot Instructions</b> na wani bot babu ko empty ne, runtime zai yi amfani da wannan global instructions. Idan bot yana da nasa instructions, nasa ne zai fi karfi.</div></div></section></div>`;
const editor=document.getElementById('global-instructions'),count=document.getElementById('instructions-count');const updateCount=()=>count.textContent=`${editor.value.length.toLocaleString()} / 50,000`;editor.addEventListener('input',updateCount);
const s=session();if(!s){feedback('Owner session ta ƙare. Ka sake login.','error');return}
const {data,error}=await sb().rpc('get_owner_instructions',{p_session:s});if(error||!data){feedback('Ba a iya loda Instructions ba. Gwada kuma.','error');return}
editor.value=String(data.instructions||'');updateCount();document.getElementById('instructions-updated').textContent=data.updated_at?`Updated ${new Date(data.updated_at).toLocaleString()}`:'Not saved yet';
document.getElementById('save-global-instructions').onclick=async()=>{const button=document.getElementById('save-global-instructions');button.disabled=true;button.textContent='Saving...';const {data:out,error:saveError}=await sb().rpc('update_owner_instructions',{p_session:s,p_instructions:editor.value});if(saveError||!out){feedback(saveError?.message==='INVALID_OWNER_SESSION'?'Owner session ta ƙare. Ka sake login.':'An kasa ajiye Instructions. Gwada kuma.','error')}else{feedback('✓ Global Instructions an ajiye su a Supabase nan take.','success');document.getElementById('instructions-updated').textContent=`Updated ${new Date(out.updated_at).toLocaleString()}`}button.disabled=false;button.textContent='Save Instructions'};
}
window.showSadeeqInstructions=render;
})();
