/* Level 13 • Sadeeq AI Owner Workspace • FIXED PAGE TARGET */
(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){return window.__sadeeqConsoleSession?.()||''}
function render(){
 const root=$('page-sadeeq');
 if(!root)return;
 root.className='page active-page';
 root.innerHTML=`<div class="module-hero"><div><span class="section-label">CREATIVE AI WORKSPACE</span><h2>Sadeeq AI</h2><p>Ka tura prompt, takarda, jarrabawa ko wani aiki. Sadeeq AI zai shirya maka output cikin tsari.</p></div><div class="module-badge">OWNER ONLY</div></div>
 <div class="sa-grid"><section class="form-panel sa-form"><div class="panel-heading"><div><span class="section-label">CREATE</span><h3>Sabon Aiki</h3></div></div>
 <label>Task / Prompt</label><textarea id="sa-prompt" rows="9" maxlength="50000" placeholder="Misali: Create a full Islamic Hospital proposal..."></textarea>
 <div class="sa-row"><div><label>Output Type</label><select id="sa-type"><option value="document">Document</option><option value="text">Text</option><option value="html">HTML</option><option value="markdown">Markdown</option><option value="json">JSON</option><option value="exam">Exam / Jarrabawa</option></select></div><div><label>Title</label><input id="sa-title" maxlength="180" placeholder="Suna / title na aikin"></div></div>
 <div class="sa-row"><div><label>Model</label><input id="sa-model" placeholder="Active model (optional)"></div><div><label>Instructions</label><input id="sa-extra" maxlength="1000" placeholder="Ƙarin umarni (optional)"></div></div>
 <div class="sa-actions"><button id="sa-create" class="primary-btn" type="button">✦ Generate</button><button id="sa-clear" class="secondary-btn" type="button">Clear</button></div><div id="sa-status" class="inline-error hidden"></div></section>
 <section class="form-panel sa-result"><div class="panel-heading"><div><span class="section-label">RESULT</span><h3>Generated Output</h3></div><div id="sa-state" class="module-status">Ready</div></div><div id="sa-output" class="sa-output"><div class="empty-state">Amsar da aka samar za ta bayyana a nan.</div></div><div id="sa-downloads" class="sa-downloads hidden"><button id="sa-copy" class="secondary-btn" type="button">Copy</button><button id="sa-download" class="primary-btn" type="button">Download</button></div></section></div>
 <section class="form-panel sa-history"><div class="panel-heading"><div><span class="section-label">RECENT</span><h3>Recent Generations</h3></div><button id="sa-refresh" class="secondary-btn" type="button">↻</button></div><div id="sa-history-list" class="empty-state">Ana loda...</div></section>`;
 bind();loadHistory();
}
function status(m,ok=false){const e=$('sa-status');if(!e)return;e.textContent=m;e.classList.remove('hidden');e.classList.toggle('success',ok)}
let current='',currentTitle='Sadeeq AI Output',currentType='document';
function bind(){$('sa-create').onclick=generate;$('sa-clear').onclick=()=>{$('sa-prompt').value='';$('sa-output').innerHTML='<div class="empty-state">Amsar da aka samar za ta bayyana a nan.</div>';$('sa-downloads').classList.add('hidden');$('sa-state').textContent='Ready';status('',true)};$('sa-copy').onclick=async()=>{await navigator.clipboard.writeText(current);status('An kwafi output.',true)};$('sa-download').onclick=download;$('sa-refresh').onclick=loadHistory}
async function generate(){const prompt=$('sa-prompt').value.trim();if(!prompt){status('Saka prompt ko aikin da kake son a kirkira.');return}$('sa-create').disabled=true;$('sa-state').textContent='Generating...';status('Sadeeq AI na aiki...');try{const r=await fetch('https://bopezesfrmdxiagvvyyh.supabase.co/functions/v1/sadeeq-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:session(),prompt,title:$('sa-title').value.trim(),output_type:$('sa-type').value,model:$('sa-model').value.trim(),extra_instructions:$('sa-extra').value.trim()})});const d=await r.json();if(!r.ok||!d.ok){status(d.error||'Generation failed.');$('sa-state').textContent='Error';return}current=String(d.output||'');currentTitle=d.title||$('sa-title').value.trim()||'Sadeeq AI Output';currentType=d.output_type||$('sa-type').value;$('sa-output').textContent=current;$('sa-downloads').classList.remove('hidden');$('sa-state').textContent='Completed';status('An gama kirkirar output.',true);loadHistory()}catch(e){$('sa-state').textContent='Network error';status('Network error wajen Sadeeq AI.')}finally{$('sa-create').disabled=false}}
function download(){const ext=currentType==='html'?'html':currentType==='json'?'json':currentType==='markdown'?'md':'txt';const mime=currentType==='html'?'text/html':currentType==='json'?'application/json':'text/plain';const blob=new Blob([current],{type:mime});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentTitle||'sadeeq-ai-output').replace(/[^a-z0-9\-_]+/gi,'-').slice(0,80)+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadHistory(){const e=$('sa-history-list');if(!e||!window.client)return;const r=await window.client.rpc('owner_list_sadeeq_jobs',{p_session:session()});if(r.error||!r.data?.ok){e.textContent='Unable to load history.';return}const rows=r.data.jobs||[];e.innerHTML=rows.length?rows.map(x=>'<button class="history-item" type="button" data-id="'+esc(x.id)+'"><strong>'+esc(x.title||'Untitled')+'</strong><span>'+esc(x.output_type||'document')+' • '+new Date(x.created_at).toLocaleString()+'</span></button>').join(''):'No generations yet.';e.querySelectorAll('.history-item').forEach(b=>b.onclick=async()=>{const r=await window.client.rpc('owner_get_sadeeq_job',{p_session:session(),p_id:b.dataset.id});if(r.data?.ok){current=String(r.data.job.output||'');currentTitle=r.data.job.title||'Sadeeq AI Output';currentType=r.data.job.output_type||'document';$('sa-output').textContent=current;$('sa-downloads').classList.remove('hidden');$('sa-state').textContent='Loaded'}})}
window.showSadeeqAI=render;
})();