/* Level 13 • Sadeeq AI Owner Workspace */
(function(){'use strict';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function session(){return window.__sadeeqConsoleSession?.()||''}let current='',currentTitle='Sadeeq AI Output',currentType='document';
function render(){const root=$('page-sadeeq');if(!root)return;root.className='page active-page';root.innerHTML=`<div class="sa-shell">
<div class="sa-hero"><div class="sa-orb">✦</div><div><span class="section-label">PRIVATE CREATIVE ENGINE</span><h2>Sadeeq AI</h2><p>Your intelligent workspace for documents, exams, ideas, designs and custom creations.</p></div><div class="sa-ready"><i></i> READY</div></div>
<div class="sa-workspace">
<section class="sa-card sa-create-card"><div class="sa-card-head"><div><span class="sa-eyebrow">CREATE SOMETHING</span><h3>What should Sadeeq create?</h3></div><span class="sa-step">01</span></div>
<div class="sa-prompt-wrap"><span class="sa-prompt-icon">✦</span><textarea id="sa-prompt" maxlength="50000" placeholder="Describe exactly what you want Sadeeq AI to create...\n\nExample: Create a complete Islamic Hospital proposal with departments, services, vision, mission and organizational structure."></textarea><div class="sa-prompt-foot"><span>⌘ Your instructions are private</span><span id="sa-count">0 / 50,000</span></div></div>
<div class="sa-templates"><span class="sa-mini-label">QUICK START</span><div class="sa-template-row"><button type="button" data-template="Create a complete Islamic Hospital proposal with professional structure, services, departments, vision and mission.">🏥 Islamic Hospital</button><button type="button" data-template="Create a professional examination paper with questions, sections, marks and answer key.">📝 Examination</button><button type="button" data-template="Create a complete business proposal with executive summary, objectives, services and financial structure.">💼 Business Proposal</button><button type="button" data-template="Create a professional school learning material with lessons, examples, exercises and answers.">🎓 School Material</button></div></div>
<div class="sa-settings"><div class="sa-field"><label>OUTPUT TYPE</label><select id="sa-type"><option value="document">📄 Document</option><option value="text">✦ Text</option><option value="html">🌐 HTML</option><option value="markdown">▤ Markdown</option><option value="json">{} JSON</option><option value="exam">📝 Exam / Jarrabawa</option></select></div><div class="sa-field"><label>TITLE</label><input id="sa-title" maxlength="180" placeholder="Title of your creation"></div><div class="sa-field"><label>MODEL</label><input id="sa-model" placeholder="Active model / automatic"></div></div>
<div class="sa-field sa-extra"><label>ADDITIONAL INSTRUCTIONS</label><input id="sa-extra" maxlength="1000" placeholder="Style, language, length or any special instruction..."></div>
<div class="sa-create-actions"><button id="sa-create" class="sa-generate" type="button"><span>✦</span> Generate with Sadeeq AI</button><button id="sa-clear" class="sa-clear" type="button">Clear</button></div><div id="sa-status" class="sa-status hidden"></div></section>
<section class="sa-card sa-result-card"><div class="sa-card-head"><div><span class="sa-eyebrow">WORKSPACE</span><h3>Generated Result</h3></div><div id="sa-state" class="sa-state"><i></i> Ready</div></div><div id="sa-output" class="sa-output"><div class="sa-empty"><div class="sa-empty-icon">✦</div><strong>Your creation will appear here</strong><span>Write a prompt and let Sadeeq AI build it for you.</span></div></div><div id="sa-downloads" class="sa-result-actions hidden"><button id="sa-copy" type="button">⧉ Copy</button><button id="sa-download" type="button">↓ Download</button><button id="sa-regenerate" type="button">↻ Regenerate</button></div></section></div>
<section class="sa-card sa-history-card"><div class="sa-card-head"><div><span class="sa-eyebrow">YOUR WORK</span><h3>Recent Generations</h3></div><button id="sa-refresh" class="sa-refresh" type="button">↻</button></div><div id="sa-history-list" class="sa-history-list"><div class="sa-empty small"><span>Loading your recent creations...</span></div></div></section></div>`;bind();loadHistory()}
function status(m,ok=false){const e=$('sa-status');if(!e)return;e.textContent=m;e.classList.remove('hidden');e.classList.toggle('ok',ok)}
function bind(){$('sa-prompt').oninput=e=>{$('sa-count').textContent=e.target.value.length.toLocaleString()+' / 50,000'};document.querySelectorAll('.sa-template-row button').forEach(b=>b.onclick=()=>{const p=$('sa-prompt');p.value=b.dataset.template;p.dispatchEvent(new Event('input'));p.focus()});$('sa-create').onclick=generate;$('sa-clear').onclick=clearAll;$('sa-copy').onclick=async()=>{await navigator.clipboard.writeText(current);status('An kwafi output.',true)};$('sa-download').onclick=download;$('sa-regenerate').onclick=generate;$('sa-refresh').onclick=loadHistory}
function clearAll(){$('sa-prompt').value='';$('sa-prompt').dispatchEvent(new Event('input'));$('sa-output').innerHTML='<div class="sa-empty"><div class="sa-empty-icon">✦</div><strong>Your creation will appear here</strong><span>Write a prompt and let Sadeeq AI build it for you.</span></div>';$('sa-downloads').classList.add('hidden');$('sa-state').innerHTML='<i></i> Ready';status('',true)}
async function generate(){const prompt=$('sa-prompt').value.trim();if(!prompt){status('Saka prompt ko zaɓi Quick Start template.');return}const btn=$('sa-create');btn.disabled=true;btn.innerHTML='<span class="sa-spinner"></span> Sadeeq is thinking...';$('sa-state').innerHTML='<i class="thinking"></i> Generating';status('Ana ƙirƙirar output...');try{const r=await fetch('https://bopezesfrmdxiagvvyyh.supabase.co/functions/v1/sadeeq-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:session(),prompt,title:$('sa-title').value.trim(),output_type:$('sa-type').value,model:$('sa-model').value.trim(),extra_instructions:$('sa-extra').value.trim()})});const d=await r.json();if(!r.ok||!d.ok){status(d.error||'Generation failed.');$('sa-state').innerHTML='<i class="error"></i> Error';return}current=String(d.output||'');currentTitle=d.title||$('sa-title').value.trim()||'Sadeeq AI Output';currentType=d.output_type||$('sa-type').value;$('sa-output').textContent=current;$('sa-downloads').classList.remove('hidden');$('sa-state').innerHTML='<i></i> Completed';status('An gama kirkirar output.',true);loadHistory()}catch(e){$('sa-state').innerHTML='<i class="error"></i> Network error';status('Network error wajen Sadeeq AI.')}finally{btn.disabled=false;btn.innerHTML='<span>✦</span> Generate with Sadeeq AI'}}
function download(){const ext=currentType==='html'?'html':currentType==='json'?'json':currentType==='markdown'?'md':'txt';const mime=currentType==='html'?'text/html':currentType==='json'?'application/json':'text/plain';const blob=new Blob([current],{type:mime});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentTitle||'sadeeq-ai-output').replace(/[^a-z0-9\-_]+/gi,'-').slice(0,80)+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadHistory(){const e=$('sa-history-list');if(!e||!window.client)return;const r=await window.client.rpc('owner_list_sadeeq_jobs',{p_session:session()});if(r.error||!r.data?.ok){e.innerHTML='<div class="sa-empty small"><span>History ba ta samu ba.</span></div>';return}const rows=r.data.jobs||[];e.innerHTML=rows.length?rows.map(x=>'<button class="sa-history-item" type="button" data-id="'+esc(x.id)+'"><span class="sa-history-type">'+esc(x.output_type||'document')+'</span><strong>'+esc(x.title||'Untitled')+'</strong><small>'+new Date(x.created_at).toLocaleString()+'</small><b>›</b></button>').join(''):'<div class="sa-empty small"><span>No generations yet.</span></div>';e.querySelectorAll('.sa-history-item').forEach(b=>b.onclick=async()=>{const r=await window.client.rpc('owner_get_sadeeq_job',{p_session:session(),p_id:b.dataset.id});if(r.data?.ok){current=String(r.data.job.output||'');currentTitle=r.data.job.title||'Sadeeq AI Output';currentType=r.data.job.output_type||'document';$('sa-output').textContent=current;$('sa-downloads').classList.remove('hidden');$('sa-state').innerHTML='<i></i> Loaded'}})}window.showSadeeqAI=render})();